config/routes.rb
Rails.application.routes.draw do

  resources :todos do
    put :sort
  end

  root to: 'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  def index
    @todos = Todo.rank(:row_order)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
# this action will be called via ajax
  def sort
    todo = Todo.find(paramss[:todo_id])
    todo.update(todo_params)
    render nothing: true
  end

  def index
    @todos = Todo.rank(:row_order)
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :row_order_position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.slim
h1 listing todos

table.table.table-bordered.table-sortable
   thead
     tr
       th Name
       th
       th
       th
   tbody
      - @todos.each do |todo|
      tr
      tr.item(data = { model_name: todo.class.name.underscore, update_url: todo_sort_path(todo) })
         td = todo.name
         td = link_to 'Show', todo
         td = link_to 'Edit', edit_todo_path(todo)
         td = link_to 'Destroy', todo, data: {:confirm => 'Are you sure?'}, :method => :delete